[package]
name = "fotke"
version = "0.1.0"
authors = ["Goran Ojkic <goran.ojkic@soundcloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
azul = { git = "https://github.com/maps4print/azul" }
